### ISSUE TITLE
Privacy warning when visiting https://laravelvoyager.com

### ISSUE THREAD

**Issue by pcate-fls** [the-control-group/voyager-site#10]
Just wanted to give you a heads up that when I visit the Voyager homepage at https://laravelvoyager.com, I'm getting a privacy warning:

![screen shot 2018-04-18 at 9 29 17 am](https://user-images.githubusercontent.com/21206327/38934952-1623c232-42eb-11e8-9f47-f5e390898485.png)

Seems to be related to https cert.

**Comment by fletch3555** [comment]
Thanks.  It was just updated.  Looks like the cert was created with the wrong hostname (`www.laravel...` instead of `laravel...`).  Thanks for the heads up! We'll get it fixed

**Comment by marktopper** [comment]
This seems to be fixed by now.
